# generate the ground truth
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN04158282/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN04158282/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN02768808/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN02768808/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN02138579/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN02138579/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016516/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016516/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016509/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016509/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016508/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016508/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016533/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016533/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016532/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016532/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016531/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016531/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016529/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016529/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016528/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016528/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016527/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016527/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016534/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016534/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016525/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016525/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016524/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016524/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016539/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016539/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016535/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016535/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016518/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016518/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016517/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016517/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016540/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016540/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016543/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016543/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016544/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016544/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016542/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016542/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016479/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016479/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016545/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN21016545/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN19931439/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN19931439/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN19931475/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN19931475/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN19931468/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN19931468/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN19931463/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN19931463/output -as -s
python /data/hoan/amromics/panta/panta.py -p init -a /data/hoan/amromics/data/ncbi/Kp_true/SAMN19931444/*.fna.gz -o /data/hoan/amromics/data/ncbi/Kp_true/SAMN19931444/output -as -s